### ISSUE TITLE
Publish doi2ietf to pip

### ISSUE THREAD

**Issue by ronaldtse** [ietf-ribose/doi2ietf-py#3]
Use the ietf-ribose-ci user with access token `IETF_RIBOSE_CI_PAT` (available in secrets) to publish.

**Comment by strogonoff** [comment]
Note that there’s no “pip” to publish to, so presumably you mean PyPI?

* `pip` is the package management utility
* PyPI is Python package index registry
* Publishing to PyPI is not required to make package installable with `pip`
  * If `setup.py` is present in the repo, it’s possible to `pip install git+https://github.com/ietf-ribose/doi2ietf-py`

**Comment by ronaldtse** [comment]
PyPI, yes. Thanks.

**Comment by yablokov** [comment]
Hi!

I tried to publish package to Test PyPi, with 

> ietf-ribose-ci user with access token IETF_RIBOSE_CI_PAT

 but got authentication error:

```
HTTPError: 403 Forbidden from https://test.pypi.org/legacy/
Invalid or non-existent authentication information. See https://test.pypi.org/help/#invalid-auth for more information.
```

Maybe I used it wrong?

**Comment by ronaldtse** [comment]
@yablokov please use this token instead for PyPi: `RIBOSE_PYPI_API_TOKEN`.

`IETF_RIBOSE_CI_PAT` is the GitHub token for the CI account.

**Comment by ronaldtse** [comment]
@yablokov please remember to make this a CLI command.

**Comment by ronaldtse** [comment]
Done for the first publish and made it into a CLI command.

**Comment by ronaldtse** [comment]
Closing.
