### ISSUE TITLE
Remaining issues

### ISSUE THREAD

**Issue by ronaldtse** [ietf-ribose/doi2ietf-py#7]
* Currently, tests in this implementation invoke Ruby gem and use the results it produces as a reference to compare with.

  * At a future stage, it’ll be wrapped into more conventional test runner and any dependency on Ruby library in tests will likely be removed, but I encouraged Vladimir to release as is since currently the tests achieve the purpose at validating the implementation.

* Vladimir noted that there appear to be issues with the Ruby implementation we take as a reference. For example, dates omit day for some reason

      "10.1002/9780470974582.ch12"
      XML element (from doilit): b'<date year="2010" month="October"/>\n'
      InsertAttrib(node='/root/reference[7]/front/date[1]', name='day', value='04')

_Originally posted by @strogonoff in https://github.com/ietf-ribose/doi2ietf-py/issues/1#issuecomment-890373326_

**Comment by ronaldtse** [comment]
I believe both issues are fixed, right? Ping @yablokov @strogonoff

**Comment by yablokov** [comment]
@ronaldtse Yes. It would be more correct to say that was issues with original ruby project. Our code must be compatible with standards, not with legacy ruby code (as I initially proposed it).

**Comment by ronaldtse** [comment]
Thanks @yablokov !
